.PHONY: main checkFn doWork

all: main checkFn doWork
binary: main checkFn doWork
opt: main checkFn doWork
compd: main checkFn doWork
match: main checkFn doWork

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
checkFn:
	@echo
	${MAKE} -C checkFn $(MAKECMDGOALS)
doWork:
	@echo
	${MAKE} -C doWork $(MAKECMDGOALS)
