.PHONY: main doOp

all: main doOp
binary: main doOp
mcsema: main doOp
opt: main doOp
compd: main doOp
match: main doOp

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
doOp:
	@echo
	${MAKE} -C doOp $(MAKECMDGOALS)
