.PHONY: main foo checkFn

all: main foo checkFn
binary: main foo checkFn
opt: main foo checkFn
compd: main foo checkFn
match: main foo checkFn

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
foo:
	@echo
	${MAKE} -C foo $(MAKECMDGOALS)
checkFn:
	@echo
	${MAKE} -C checkFn $(MAKECMDGOALS)
