.PHONY: main doTrans

all: main doTrans
binary: main doTrans
opt: main doTrans
compd: main doTrans
match: main doTrans

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
doTrans:
	@echo
	${MAKE} -C doTrans $(MAKECMDGOALS)
