.PHONY: foo main

all: foo main
binary: foo main
mcsema: foo main
opt: foo main
compd: foo main
match: foo main

foo:
	@echo
	${MAKE} -C foo $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
