.PHONY: main demo3

all: main demo3
binary: main demo3
opt: main demo3
compd: main demo3
match: main demo3

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
demo3:
	@echo
	${MAKE} -C demo3 $(MAKECMDGOALS)
