.PHONY: main switches

all: main switches
binary: main switches
mcsema: main switches
opt: main switches
compd: main switches
match: main switches

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
switches:
	@echo
	${MAKE} -C switches $(MAKECMDGOALS)
