.PHONY: binary_search main

all: binary_search main
binary: binary_search main
mcsema: binary_search main
opt: binary_search main
compd: binary_search main
match: binary_search main

binary_search:
	@echo
	${MAKE} -C binary_search $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
