.PHONY: Ack main

all: Ack main
binary: Ack main
mcsema: Ack main
opt: Ack main
compd: Ack main
match: Ack main

Ack:
	@echo
	${MAKE} -C Ack $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
