.PHONY: update main

all: update main
binary: update main
mcsema: update main
opt: update main
compd: update main
match: update main

update:
	@echo
	${MAKE} -C update $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
