.PHONY: sum_2_n main

all: sum_2_n main
binary: sum_2_n main
mcsema: sum_2_n main
opt: sum_2_n main
compd: sum_2_n main
match: sum_2_n main

sum_2_n:
	@echo
	${MAKE} -C sum_2_n $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
