.PHONY: add_sub main

all: add_sub main
binary: add_sub main
mcsema: add_sub main
opt: add_sub main
compd: add_sub main
match: add_sub main

add_sub:
	@echo
	${MAKE} -C add_sub $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
