.PHONY: DoDemoFpu1 main timespi

all: DoDemoFpu1 main timespi
binary: DoDemoFpu1 main timespi
opt: DoDemoFpu1 main timespi
compd: DoDemoFpu1 main timespi
match: DoDemoFpu1 main timespi

DoDemoFpu1:
	@echo
	${MAKE} -C DoDemoFpu1 $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
timespi:
	@echo
	${MAKE} -C timespi $(MAKECMDGOALS)
