

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2015 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-38F3-7EE4-0C			    |
; |			    University of Illinois			    |
; +-------------------------------------------------------------------------+
;
; Input	SHA256 : 868E79D98CE9150B9471A0979CC06C325ACF12EE93D39B4E0E5FC2BAEC7F0D44
; Input	MD5    : 2106BA9705E5FA484E568BA5160BBBFC
; Input	CRC32  : 44CF2F09

; File Name   :	/home/sdasgup3/Github/validating-binary-decompilation/tests/sum_2_n/sum_2_n
; Format      :	ELF64 for x86-64 (Shared object)
; Interpreter '/lib64/ld-linux-x86-64.so.2'
; Needed Library 'libc.so.6'
;
; Source File :	'crtstuff.c'
; Source File :	'sum_2_n.c'
; Source File :	'crtstuff.c'

		.686p
		.mmx
		.model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_init		segment	dword public 'CODE' use64
		assume cs:_init
		;org 4F8h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _init_proc
_init_proc	proc near		; CODE XREF: __libc_csu_init+2Cp
		sub	rsp, 8		; _init
		mov	rax, cs:__gmon_start___ptr
		test	rax, rax
		jz	short loc_50A
		call	rax ; __gmon_start__

loc_50A:				; CODE XREF: _init_proc+Ej
		add	rsp, 8
		retn
_init_proc	endp

_init		ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_plt		segment	para public 'CODE' use64
		assume cs:_plt
		;org 510h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		push	cs:qword_200FC0
		jmp	cs:qword_200FC8
; ---------------------------------------------------------------------------
		align 20h
_plt		ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
; Segment alignment 'qword' can not be represented in assembly
_plt_got	segment	para public 'CODE' use64
		assume cs:_plt_got
		;org 520h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
; [00000006 BYTES: COLLAPSED FUNCTION __cxa_finalize. PRESS CTRL-NUMPAD+ TO EXPAND]
		align 8
_plt_got	ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text		segment	para public 'CODE' use64
		assume cs:_text
		;org 530h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: noreturn

		public _start
_start		proc near
		xor	ebp, ebp
		mov	r9, rdx		; rtld_fini
		pop	rsi		; argc
		mov	rdx, rsp	; ubp_av
		and	rsp, 0FFFFFFFFFFFFFFF0h
		push	rax
		push	rsp		; stack_end
		lea	r8, __libc_csu_fini ; fini
		lea	rcx, __libc_csu_init ; init
		lea	rdi, main	; main
		call	cs:__libc_start_main_ptr
		hlt
_start		endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

deregister_tm_clones proc near		; CODE XREF: __do_global_dtors_aux:loc_613p
		lea	rdi, __bss_start
		lea	rax, unk_201017
		push	rbp
		sub	rax, rdi
		mov	rbp, rsp
		cmp	rax, 0Eh
		jbe	short loc_590
		mov	rax, cs:_ITM_deregisterTMCloneTable_ptr
		test	rax, rax
		jz	short loc_590
		pop	rbp
		jmp	rax
; ---------------------------------------------------------------------------
		align 10h

loc_590:				; CODE XREF: deregister_tm_clones+19j
					; deregister_tm_clones+25j
		pop	rbp
		retn
deregister_tm_clones endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

register_tm_clones proc	near		; CODE XREF: frame_dummy:loc_63Dj
					; frame_dummy+2Bj
		lea	rdi, __bss_start
		lea	rsi, __bss_start
		push	rbp
		sub	rsi, rdi
		mov	rbp, rsp
		sar	rsi, 3
		mov	rax, rsi
		shr	rax, 3Fh
		add	rsi, rax
		sar	rsi, 1
		jz	short loc_5E0
		mov	rax, cs:_ITM_registerTMCloneTable_ptr
		test	rax, rax
		jz	short loc_5E0
		pop	rbp
		jmp	rax
; ---------------------------------------------------------------------------
		align 20h

loc_5E0:				; CODE XREF: register_tm_clones+26j
					; register_tm_clones+32j
		pop	rbp
		retn
register_tm_clones endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================


__do_global_dtors_aux proc near		; DATA XREF: .fini_array:__do_global_dtors_aux_fini_array_entryo
		cmp	cs:__bss_start,	0
		jnz	short locret_620
		cmp	cs:__cxa_finalize_ptr, 0
		push	rbp
		mov	rbp, rsp
		jz	short loc_613
		mov	rdi, cs:__dso_handle
		call	__cxa_finalize

loc_613:				; CODE XREF: __do_global_dtors_aux+15j
		call	deregister_tm_clones
		pop	rbp
		mov	cs:__bss_start,	1

locret_620:				; CODE XREF: __do_global_dtors_aux+7j
		rep retn
__do_global_dtors_aux endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================


frame_dummy	proc near		; DATA XREF: .init_array:__frame_dummy_init_array_entryo
		lea	rdi, __JCR_LIST__
		cmp	qword ptr [rdi], 0
		jnz	short loc_648

loc_63D:				; CODE XREF: frame_dummy+22j
		jmp	register_tm_clones
; ---------------------------------------------------------------------------
		align 8

loc_648:				; CODE XREF: frame_dummy+Bj
		mov	rax, cs:_Jv_RegisterClasses_ptr
		test	rax, rax
		jz	short loc_63D
		push	rbp
		mov	rbp, rsp
		call	rax ; _Jv_RegisterClasses
		pop	rbp
		jmp	register_tm_clones
frame_dummy	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

		public sum_2_n
sum_2_n		proc near		; CODE XREF: main+9p

var_14		= dword	ptr -14h
var_8		= dword	ptr -8
var_4		= dword	ptr -4

		push	rbp
		mov	rbp, rsp
		mov	[rbp+var_14], edi
		mov	[rbp+var_8], 0
		mov	[rbp+var_4], 0
		jmp	short loc_681
; ---------------------------------------------------------------------------

loc_677:				; CODE XREF: sum_2_n+27j
		mov	eax, [rbp+var_4]
		add	[rbp+var_8], eax
		add	[rbp+var_4], 1

loc_681:				; CODE XREF: sum_2_n+15j
		mov	eax, [rbp+var_4]
		cmp	eax, [rbp+var_14]
		jl	short loc_677
		mov	eax, [rbp+var_8]
		pop	rbp
		retn
sum_2_n		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int argc, const char	**argv,	const char **envp)
		public main
main		proc near		; DATA XREF: _start+1Do
		push	rbp
		mov	rbp, rsp
		mov	edi, 0Ah
		call	sum_2_n
		pop	rbp
		retn
main		endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================


; void _libc_csu_init(void)
		public __libc_csu_init
__libc_csu_init	proc near		; DATA XREF: _start+16o
		push	r15
		push	r14
		mov	r15d, edi
		push	r13
		push	r12
		lea	r12, __frame_dummy_init_array_entry
		push	rbp
		lea	rbp, __do_global_dtors_aux_fini_array_entry
		push	rbx
		mov	r14, rsi
		mov	r13, rdx
		sub	rbp, r12
		sub	rsp, 8
		sar	rbp, 3
		call	_init_proc
		test	rbp, rbp
		jz	short loc_6F6
		xor	ebx, ebx
		nop	dword ptr [rax+rax+00000000h]

loc_6E0:				; CODE XREF: __libc_csu_init+54j
		mov	rdx, r13
		mov	rsi, r14
		mov	edi, r15d
		call	qword ptr [r12+rbx*8]
		add	rbx, 1
		cmp	rbp, rbx
		jnz	short loc_6E0

loc_6F6:				; CODE XREF: __libc_csu_init+34j
		add	rsp, 8
		pop	rbx
		pop	rbp
		pop	r12
		pop	r13
		pop	r14
		pop	r15
		retn
__libc_csu_init	endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================


; void _libc_csu_fini(void)
		public __libc_csu_fini
__libc_csu_fini	proc near		; DATA XREF: _start+Fo
		rep retn
__libc_csu_fini	endp

_text		ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_fini		segment	dword public 'CODE' use64
		assume cs:_fini
		;org 714h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _term_proc
_term_proc	proc near
		sub	rsp, 8		; _fini
		add	rsp, 8
		retn
_term_proc	endp

_fini		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_rodata		segment	dword public 'CONST' use64
		assume cs:_rodata
		;org 720h
		public _IO_stdin_used
_IO_stdin_used	db    1
		db    0
		db    2
		db    0
_rodata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_eh_frame_hdr	segment	dword public 'CONST' use64
		assume cs:_eh_frame_hdr
		;org 724h
__GNU_EH_FRAME_HDR db	 1
		db  1Bh
		db    3
		db  3Bh	; ;
		db  40h	; @
		db    0
		db    0
		db    0
		db    7
		db    0
		db    0
		db    0
		db 0ECh	; ì
		db 0FDh	; ý
		db 0FFh
		db 0FFh
		db  8Ch	; Œ
		db    0
		db    0
		db    0
		db 0FCh	; ü
		db 0FDh	; ý
		db 0FFh
		db 0FFh
		db 0B4h	; ´
		db    0
		db    0
		db    0
		db  0Ch
		db 0FEh	; þ
		db 0FFh
		db 0FFh
		db  5Ch	; \
		db    0
		db    0
		db    0
		db  3Ch	; <
		db 0FFh
		db 0FFh
		db 0FFh
		db 0CCh	; Ì
		db    0
		db    0
		db    0
		db  6Ah	; j
		db 0FFh
		db 0FFh
		db 0FFh
		db 0ECh	; ì
		db    0
		db    0
		db    0
		db  7Ch	; |
		db 0FFh
		db 0FFh
		db 0FFh
		db  0Ch
		db    1
		db    0
		db    0
		db 0ECh	; ì
		db 0FFh
		db 0FFh
		db 0FFh
		db  54h	; T
		db    1
		db    0
		db    0
_eh_frame_hdr	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
; Segment alignment 'qword' can not be represented in assembly
_eh_frame	segment	para public 'CONST' use64
		assume cs:_eh_frame
		;org 768h
		db  14h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    1
		db  7Ah	; z
		db  52h	; R
		db    0
		db    1
		db  78h	; x
		db  10h
		db    1
		db  1Bh
		db  0Ch
		db    7
		db    8
		db  90h	; 
		db    1
		db    7
		db  10h
		db  14h
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db 0A8h	; ¨
		db 0FDh	; ý
		db 0FFh
		db 0FFh
		db  2Bh	; +
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  14h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    1
		db  7Ah	; z
		db  52h	; R
		db    0
		db    1
		db  78h	; x
		db  10h
		db    1
		db  1Bh
		db  0Ch
		db    7
		db    8
		db  90h	; 
		db    1
		db    0
		db    0
		db  24h	; $
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  58h	; X
		db 0FDh	; ý
		db 0FFh
		db 0FFh
		db  10h
		db    0
		db    0
		db    0
		db    0
		db  0Eh
		db  10h
		db  46h	; F
		db  0Eh
		db  18h
		db  4Ah	; J
		db  0Fh
		db  0Bh
		db  77h	; w
		db    8
		db  80h	; €
		db    0
		db  3Fh	; ?
		db  1Ah
		db  3Bh	; ;
		db  2Ah	; *
		db  33h	; 3
		db  24h	; $
		db  22h	; "
		db    0
		db    0
		db    0
		db    0
		db  14h
		db    0
		db    0
		db    0
		db  44h	; D
		db    0
		db    0
		db    0
		db  40h	; @
		db 0FDh	; ý
		db 0FFh
		db 0FFh
		db    8
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  5Ch	; \
		db    0
		db    0
		db    0
		db  68h	; h
		db 0FEh	; þ
		db 0FFh
		db 0FFh
		db  2Eh	; .
		db    0
		db    0
		db    0
		db    0
		db  41h	; A
		db  0Eh
		db  10h
		db  86h	; †
		db    2
		db  43h	; C
		db  0Dh
		db    6
		db  69h	; i
		db  0Ch
		db    7
		db    8
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  7Ch	; |
		db    0
		db    0
		db    0
		db  76h	; v
		db 0FEh	; þ
		db 0FFh
		db 0FFh
		db  10h
		db    0
		db    0
		db    0
		db    0
		db  41h	; A
		db  0Eh
		db  10h
		db  86h	; †
		db    2
		db  43h	; C
		db  0Dh
		db    6
		db  4Bh	; K
		db  0Ch
		db    7
		db    8
		db    0
		db    0
		db    0
		db  44h	; D
		db    0
		db    0
		db    0
		db  9Ch	; œ
		db    0
		db    0
		db    0
		db  68h	; h
		db 0FEh	; þ
		db 0FFh
		db 0FFh
		db  65h	; e
		db    0
		db    0
		db    0
		db    0
		db  42h	; B
		db  0Eh
		db  10h
		db  8Fh	; 
		db    2
		db  42h	; B
		db  0Eh
		db  18h
		db  8Eh	; Ž
		db    3
		db  45h	; E
		db  0Eh
		db  20h
		db  8Dh	; 
		db    4
		db  42h	; B
		db  0Eh
		db  28h	; (
		db  8Ch	; Œ
		db    5
		db  48h	; H
		db  0Eh
		db  30h	; 0
		db  86h	; †
		db    6
		db  48h	; H
		db  0Eh
		db  38h	; 8
		db  83h	; ƒ
		db    7
		db  4Dh	; M
		db  0Eh
		db  40h	; @
		db  72h	; r
		db  0Eh
		db  38h	; 8
		db  41h	; A
		db  0Eh
		db  30h	; 0
		db  41h	; A
		db  0Eh
		db  28h	; (
		db  42h	; B
		db  0Eh
		db  20h
		db  42h	; B
		db  0Eh
		db  18h
		db  42h	; B
		db  0Eh
		db  10h
		db  42h	; B
		db  0Eh
		db    8
		db    0
		db  14h
		db    0
		db    0
		db    0
		db 0E4h	; ä
		db    0
		db    0
		db    0
		db  90h	; 
		db 0FEh	; þ
		db 0FFh
		db 0FFh
		db    2
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
__FRAME_END__	db    0
		db    0
		db    0
		db    0
_eh_frame	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_init_array	segment	para public 'DATA' use64
		assume cs:_init_array
		;org 200DE0h
__frame_dummy_init_array_entry dq offset frame_dummy ; DATA XREF: __libc_csu_init+Bo
_init_array	ends			; Alternative name is '__init_array_start'

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_fini_array	segment	para public 'DATA' use64
		assume cs:_fini_array
		;org 200DE8h
__do_global_dtors_aux_fini_array_entry dq offset __do_global_dtors_aux
					; DATA XREF: __libc_csu_init+13o
_fini_array	ends			; Alternative name is '__init_array_end'

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_jcr		segment	para public 'DATA' use64
		assume cs:_jcr
		;org 200DF0h
__JCR_LIST__	db    0			; DATA XREF: frame_dummyo
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
_jcr		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_got		segment	para public 'DATA' use64
		assume cs:_got
		;org 200FB8h
_GLOBAL_OFFSET_TABLE_ dq 200DF8h
qword_200FC0	dq 0			; DATA XREF: .plt:0000000000000510r
qword_200FC8	dq 0			; DATA XREF: .plt:0000000000000516r
_ITM_deregisterTMCloneTable_ptr	dq offset _ITM_deregisterTMCloneTable
					; DATA XREF: deregister_tm_clones+1Br
__libc_start_main_ptr dq offset	__libc_start_main ; DATA XREF: _start+24r
__gmon_start___ptr dq offset __gmon_start__ ; DATA XREF: _init_proc+4r
_Jv_RegisterClasses_ptr	dq offset _Jv_RegisterClasses ;	DATA XREF: frame_dummy:loc_648r
_ITM_registerTMCloneTable_ptr dq offset	_ITM_registerTMCloneTable
					; DATA XREF: register_tm_clones+28r
__cxa_finalize_ptr dq offset __imp___cxa_finalize ; DATA XREF: __cxa_finalizer
					; __do_global_dtors_aux+9r
_got		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_data		segment	para public 'DATA' use64
		assume cs:_data
		;org 201000h
		public __data_start ; weak
__data_start	db    0			; Alternative name is '__data_start'
					; data_start
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		public __dso_handle
__dso_handle	dq offset __dso_handle	; DATA XREF: __do_global_dtors_aux+17r
					; .data:__dso_handleo
_data		ends

; ===========================================================================

; Segment type:	Uninitialized
; Segment permissions: Read/Write
_bss		segment	byte public 'BSS' use64
		assume cs:_bss
		;org 201010h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		public __bss_start
__bss_start	db ?			; DATA XREF: deregister_tm_cloneso
					; register_tm_cloneso ...
					; Alternative name is '__TMC_END__'
					; completed.7561
					; _edata
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
unk_201017	db    ?	;		; DATA XREF: deregister_tm_clones+7o
_bss		ends

; ===========================================================================

; Segment type:	Externs
; extern
		extrn __libc_start_main@@GLIBC_2_2_5:near
		extrn __cxa_finalize@@GLIBC_2_2_5:near ; weak
; int __cdecl _libc_start_main(int (__cdecl *main)(int,	char **, char **), int argc, char **ubp_av, void (*init)(void),	void (*fini)(void), void (*rtld_fini)(void), void *stack_end)
		extrn __libc_start_main:near ; CODE XREF: _start+24p
					; DATA XREF: .got:__libc_start_main_ptro
		extrn __imp___cxa_finalize:near	; weak ; DATA XREF: .got:__cxa_finalize_ptro
		extrn _ITM_deregisterTMCloneTable ; weak
					; DATA XREF: .got:_ITM_deregisterTMCloneTable_ptro
		extrn __gmon_start__:near ; weak ; CODE	XREF: _init_proc+10p
					; DATA XREF: .got:__gmon_start___ptro
		extrn _Jv_RegisterClasses:near ; weak ;	CODE XREF: frame_dummy+28p
					; DATA XREF: .got:_Jv_RegisterClasses_ptro
		extrn _ITM_registerTMCloneTable	; weak
					; DATA XREF: .got:_ITM_registerTMCloneTable_ptro


		end _start
