.PHONY: fib main

all: fib main
binary: fib main
mcsema: fib main
opt: fib main
compd: fib main
match: fib main

fib:
	@echo
	${MAKE} -C fib $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
