.PHONY: func main

all: func main
binary: func main
mcsema: func main
opt: func main
compd: func main
match: func main

func:
	@echo
	${MAKE} -C func $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
