.PHONY: main printit

all: main printit
binary: main printit
opt: main printit
compd: main printit
match: main printit

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
printit:
	@echo
	${MAKE} -C printit $(MAKECMDGOALS)
