.PHONY: get_sign main

all: get_sign main
binary: get_sign main
opt: get_sign main
compd: get_sign main
match: get_sign main

get_sign:
	@echo
	${MAKE} -C get_sign $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
