.PHONY: main printdata

all: main printdata
binary: main printdata
mcsema: main printdata
opt: main printdata
compd: main printdata
match: main printdata

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
printdata:
	@echo
	${MAKE} -C printdata $(MAKECMDGOALS)
