.PHONY:array_reverse main 

all:array_reverse main 
binary:array_reverse main 
mcsema:array_reverse main 
opt:array_reverse main 
compd:array_reverse main 

array_reverse:
	@echo
	${MAKE} -C array_reverse $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
