.PHONY: main shiftit

all: main shiftit
binary: main shiftit
opt: main shiftit
compd: main shiftit
match: main shiftit

main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
shiftit:
	@echo
	${MAKE} -C shiftit $(MAKECMDGOALS)
