.PHONY: check main

all: check main
binary: check main
mcsema: check main
opt: check main
compd: check main
match: check main

check:
	@echo
	${MAKE} -C check $(MAKECMDGOALS)
main:
	@echo
	${MAKE} -C main $(MAKECMDGOALS)
